// Code generated by mockery v2.53.5. DO NOT EDIT.

package discovery

import (
	context "context"

	model "github.com/danesparza/fxcontrol/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockScanner is an autogenerated mock type for the Scanner type
type MockScanner struct {
	mock.Mock
}

type MockScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScanner) EXPECT() *MockScanner_Expecter {
	return &MockScanner_Expecter{mock: &_m.Mock}
}

// Scan provides a mock function with given fields: _a0
func (_m *MockScanner) Scan(_a0 context.Context) ([]model.Service, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 []model.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Service, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Service); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScanner_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockScanner_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockScanner_Expecter) Scan(_a0 interface{}) *MockScanner_Scan_Call {
	return &MockScanner_Scan_Call{Call: _e.mock.On("Scan", _a0)}
}

func (_c *MockScanner_Scan_Call) Run(run func(_a0 context.Context)) *MockScanner_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockScanner_Scan_Call) Return(_a0 []model.Service, _a1 error) *MockScanner_Scan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScanner_Scan_Call) RunAndReturn(run func(context.Context) ([]model.Service, error)) *MockScanner_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScanner creates a new instance of MockScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScanner {
	mock := &MockScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
