// Code generated by mockery v2.53.5. DO NOT EDIT.

package api

import (
	model "github.com/danesparza/fxcontrol/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockDiscoveryCache is an autogenerated mock type for the DiscoveryCache type
type MockDiscoveryCache struct {
	mock.Mock
}

type MockDiscoveryCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDiscoveryCache) EXPECT() *MockDiscoveryCache_Expecter {
	return &MockDiscoveryCache_Expecter{mock: &_m.Mock}
}

// Snapshot provides a mock function with no fields
func (_m *MockDiscoveryCache) Snapshot() []model.Service {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 []model.Service
	if rf, ok := ret.Get(0).(func() []model.Service); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Service)
		}
	}

	return r0
}

// MockDiscoveryCache_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockDiscoveryCache_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *MockDiscoveryCache_Expecter) Snapshot() *MockDiscoveryCache_Snapshot_Call {
	return &MockDiscoveryCache_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *MockDiscoveryCache_Snapshot_Call) Run(run func()) *MockDiscoveryCache_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDiscoveryCache_Snapshot_Call) Return(_a0 []model.Service) *MockDiscoveryCache_Snapshot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDiscoveryCache_Snapshot_Call) RunAndReturn(run func() []model.Service) *MockDiscoveryCache_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDiscoveryCache creates a new instance of MockDiscoveryCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDiscoveryCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDiscoveryCache {
	mock := &MockDiscoveryCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
